### ISSUE TITLE
URL is broken...

### ISSUE THREAD

**Issue by Shadrock** [USAID/tracing-guide#1]
Insert sound of sad, lonely, Tuba here...

**Comment by cmurphyUSAID** [comment]
Organizations can only publish from master branch.

Merge the gh-pages branch to the master branch and then regenerate the pages.

**Comment by cmurphyUSAID** [comment]
Done.

**Comment by Shadrock** [comment]
That did it, Chris, thanks! Just so you know: I'm not on as a member and, therefore, can't make these types of fixes.
